# ===========================================
# 基本アクセステスト
# ===========================================

# ローカル
GET http://localhost:3000/
Accept: application/json

# 本番
GET http://52.199.151.155:3000/
Accept: application/json
